# Generated by Django 5.2.15 on 2026-07-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_attendance_is_present_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='College or institution name', max_length=200)),
                ('course', models.CharField(max_length=150)),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Total course hours')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Total course days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='student',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Course duration in days'),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Course duration in hours'),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional batch/group this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.batch'),
        ),
    ]
