# Generated by Django 5.2.15 on 2026-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_batch_remove_student_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course_type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', help_text='Short Term: hours & days | Long Term: months', max_length=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='duration_months',
            field=models.PositiveIntegerField(default=0, help_text='Total course months (long term)'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', help_text='Short Term: hours & days | Long Term: months', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_months',
            field=models.PositiveIntegerField(default=0, help_text='Course duration in months'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Total course days (short term)'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total course hours (short term)'),
        ),
    ]
